---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/wsaults/HomeObserverBackend.git
    branch: master

- name: cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}

jobs:
  - name: build
    public: true
    plan:
      - get: source-code
        trigger: true
      - task: build
        file: source-code/ci/build.yml
      - put: cf
        params:
          manifest: source-code/manifest.yml
          path: build-output/Home-Observer-Backend-0.0.1-SNAPSHOT.jar